services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - /home/usuario/Documents/projects/blumbit:/controllers
    networks:
      - postgres-network
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: supermercad_db
    ports:
      - "5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-network
volumes:
  postgres-volume:
networks:
  postgres-network:
